spring:
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
    default-property-inclusion: non_null
  datasource:
    name: user-server
    url: jdbc:mysql://${MYSQL_HOST:139.9.206.164}:${MYSQL_PORT:3306}/cloud_deer_admin?useUnicode=true&characterEncoding=UTF8&useSSL=false&serverTimezone=GMT%2B8
    username: root
    password: King1992!
    # 使用druid数据源
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
  redis:
    host: ${REDIS_HOST:139.9.206.164}
    port:  ${REDIS_PORT:6379}
    password: king1278
    timeout: 2000ms
    database: 0
    jedis:
      pool:
        max-active: 300
        max-idle: 100
        max-wait: -1s
  rabbitmq:
    host: 139.9.206.164
    port: 5672
    username: guest
    password: guest
